apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chart:
    spec:
      # https://artifacthub.io/packages/helm/cert-manager/cert-manager
      chart: cert-manager
  values:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::626635402027:role/vozzo-prod-aps1/vozzo-prod-aps1-cert-manager-sa
    nodeSelector:
      workload-type: opz-graviton
    tolerations:
    - key: "workload-type"
      operator: "Equal"
      value: "opz-graviton"
      effect: "PreferNoSchedule"
    webhook:
      nodeSelector:
        workload-type: opz-graviton
      tolerations:
      - key: "workload-type"
        operator: "Equal"
        value: "opz-graviton"
    cainjector:
      nodeSelector:
        workload-type: opz-graviton
      tolerations:
      - key: "workload-type"
        operator: "Equal"
        value: "opz-graviton"
