apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-community
  namespace: flux-system
spec:
  type: "oci"
  interval: 6h
  url: oci://ghcr.io/grafana-community/helm-charts
